<%@ page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<div id="footer">
	<span class="footer">
		Generated by Coline, Reda, Gaétan & Babacar | Copyright &copy; 2016 All Rights Reserved
	</span> 
</div>